version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cinema_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: mouadmaa
      POSTGRES_PASSWORD: P@ssw0rd123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mouadmaa -d cinema_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
